packages:
  - "apps/*"
  - "packages/*"
  - "playground"
  - "docs"
  - "internal/*"
  - "primitives/*"

catalog:
  # Core dependencies
  'typescript': 5.8.2
  'eslint': 9.39.0

  # Build tools
  'tsdown': 0.16.6
  'tsx': 4.20.3

  # React ecosystem
  'react': 19.1.0
  'react-dom': 19.1.0
  'lucide-react': 0.525.0
  'babel-plugin-react-compiler': 1.0.0

  # Next.js
  'next': 16.0.3
  '@next/mdx': 16.0.3
  '@next/eslint-plugin-next': 15.2.4

  # UI & Styling
  '@radix-ui/react-slot': 1.2.3
  'clsx': 2.1.1
  'next-themes': 0.4.6
  'tailwindcss': 4.1.17

  # Types
  '@types/node': 22.15.3
  '@types/react': 19.1.0
  '@types/react-dom': 19.1.1

  # UI utilities
  '@iconify/react': 6.0.0
  'tailwind-merge': 3.3.0
  'tailwind-variants': 3.1.1
  'rimraf': 6.0.1
  'shiki': 3.13.0
  'unist-util-visit': 5.0.0
  'consola': 3.3.0
  'kolorist': 1.8.0
  'tailwindcss-animate': 1.0.7
  'tw-animate-css': 1.3.6
  '@tailwindcss/postcss': 4.1.16

  # UnoCSS
  '@unocss/core': 66.3.2
  '@unocss/eslint-config': 66.3.2

  # ESLint plugins - Core
  '@eslint/js': 9.39.0
  '@eslint/markdown': 7.5.1
  '@eslint/eslintrc': 3.2.0
  'eslint-config-next': 16.0.0

  # ESLint plugins - TypeScript
  '@typescript-eslint/eslint-plugin': 8.46.0
  '@typescript-eslint/parser': 8.46.0

  # ESLint plugins - React
  'eslint-plugin-react': 7.37.5
  'eslint-plugin-react-hooks': 7.0.0
  'eslint-plugin-react-native': 5.0.0
  'eslint-plugin-react-refresh': 0.4.24

  # ESLint plugins - Vue
  'eslint-plugin-vue': 10.5.1
  'eslint-processor-vue-blocks': 0.1.2
  'vue-eslint-parser': 10.2.0

  # ESLint plugins - Import/Export
  'eslint-plugin-import-lite': 0.3.0
  'eslint-plugin-import-x': 4.16.1
  'eslint-plugin-unused-imports': 4.3.0

  # ESLint plugins - Code Quality
  '@eslint-community/eslint-plugin-eslint-comments': 4.4.1
  '@vitest/eslint-plugin': 1.4.3
  'eslint-plugin-antfu': 3.1.1
  'eslint-plugin-command': 3.3.1
  'eslint-plugin-erasable-syntax-only': 0.4.0
  'eslint-plugin-jsdoc': 61.4.1
  'eslint-plugin-n': 17.23.0
  'eslint-plugin-no-only-tests': 3.3.0
  'eslint-plugin-perfectionist': 4.15.1
  'eslint-plugin-pnpm': 1.3.0
  'eslint-plugin-prettier': 5.5.4
  'eslint-plugin-regexp': 2.10.0
  'eslint-plugin-sort': 4.0.0
  'eslint-plugin-unicorn': 62.0.0

  # ESLint plugins - Styling
  '@stylistic/eslint-plugin': 5.6.1
  'eslint-plugin-tailwindcss': 4.0.0-beta.0

  # ESLint plugins - File Formats
  'eslint-plugin-jsonc': 2.21.0
  'eslint-plugin-mdx': 3.6.2
  'eslint-plugin-toml': 0.12.0
  'eslint-plugin-yml': 1.19.0
  'eslint-mdx': 3.6.2

  # ESLint utilities
  'eslint-config-flat-gitignore': 2.1.0
  'eslint-flat-config-utils': 0.4.0
  'eslint-merge-processors': 0.1.0
  'eslint-parser-plain': 0.1.1
  'jsonc-eslint-parser': 2.4.1
  'toml-eslint-parser': 0.10.0
  'yaml-eslint-parser': 1.3.0
