packages:
  - "apps/*"
  - "packages/*"
  - "playground"
  - "docs"
  - "internal/*"
  - "primitives/*"

catalog:
  # Core dependencies
  'typescript': 5.8.2
  'eslint': 9.30.0

  # Build tools
  'tsdown': 0.16.6
  'tsx': 4.20.3

  # React ecosystem
  'react': 19.1.0
  'react-dom': 19.1.0
  'lucide-react': 0.525.0

  # Next.js
  'next': 16.0.3
  '@next/mdx': 16.0.3

  # UI & Styling
  '@radix-ui/react-slot': 1.2.3
  'clsx': 2.1.1
  'next-themes': 0.4.6
  'tailwindcss': 4.1.17

  # Types
  '@types/node': 22.15.3
  '@types/react': 19.1.0
  '@types/react-dom': 19.1.1

  # UI utilities
  '@iconify/react': 6.0.0
  'tailwind-merge': 3.3.0
  'tailwind-variants': 3.1.1
  'rimraf': 6.0.1
  'shiki': 3.13.0
  'unist-util-visit': 5.0.0
  'consola': 3.3.0
  'kolorist': 1.8.0
  'tailwindcss-animate': 1.0.7
  'tw-animate-css': 1.3.6
  '@tailwindcss/postcss': 4.1.16
